import { Source_Sans_3 } from "next/font/google";
import "@/styles/components.css";
import "@/styles/fonts.css";
import "@/app/globals.css";



const sourceSans = Source_Sans_3({
  subsets: ['latin'],
  variable: '--font-source-sans',
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sourceSans.className}>
        {children}
      </body>
    </html>
  );
}
